/*
 * SPDX-FileCopyrightText: 2022-2026 Espressif Systems (Shanghai) CO LTD
 *
 * SPDX-License-Identifier: Apache-2.0
 */

/**
 * @file
 * @brief This file was generated by esp_mmap_assets, don't modify it
 */

#pragma once

#include "esp_mmap_assets.h"

#define MMAP_COFFEE_PJPG_FILES           51
#define MMAP_COFFEE_PJPG_CHECKSUM        0x810F

enum MMAP_COFFEE_PJPG_LISTS {
    MMAP_COFFEE_PJPG_BG_PJPG = 0,        /*!< BG.pjpg */
    MMAP_COFFEE_PJPG_BREWING_PJPG = 1,        /*!< Brewing.pjpg */
    MMAP_COFFEE_PJPG_COFFEE_ILLUSTRATION_PJPG = 2,        /*!< Coffee_illustration.pjpg */
    MMAP_COFFEE_PJPG_ARROWS_PJPG = 3,        /*!< arrows.pjpg */
    MMAP_COFFEE_PJPG_BEANICONS_PJPG = 4,        /*!< beanicons.pjpg */
    MMAP_COFFEE_PJPG_BIG_ESPRESSO_PJPG = 5,        /*!< big_espresso.pjpg */
    MMAP_COFFEE_PJPG_BIG_LATTE_PJPG = 6,        /*!< big_latte.pjpg */
    MMAP_COFFEE_PJPG_BIG_RISTRETTO_PJPG = 7,        /*!< big_ristretto.pjpg */
    MMAP_COFFEE_PJPG_ESPRESSO_PJPG = 8,        /*!< espresso.pjpg */
    MMAP_COFFEE_PJPG_LATTE_ILLUSTRATION_PJPG = 9,        /*!< latte_illustration.pjpg */
    MMAP_COFFEE_PJPG_SHAPE1_PJPG = 10,        /*!< shape1.pjpg */
    MMAP_COFFEE_PJPG_TANK_PJPG = 11,        /*!< tank.pjpg */
    MMAP_COFFEE_PJPG_PLAY_BUTTON_PNG = 12,        /*!< Play_button.png */
    MMAP_COFFEE_PJPG_POLYGON_PNG = 13,        /*!< Polygon.png */
    MMAP_COFFEE_PJPG_TOP_PNG = 14,        /*!< Top.png */
    MMAP_COFFEE_PJPG_ALERT_PNG = 15,        /*!< alert.png */
    MMAP_COFFEE_PJPG_ARROW_PNG = 16,        /*!< arrow.png */
    MMAP_COFFEE_PJPG_BEANS_WHITE_PNG = 17,        /*!< beans_white.png */
    MMAP_COFFEE_PJPG_BIGBEAN_PNG = 18,        /*!< bigbean.png */
    MMAP_COFFEE_PJPG_BLE_PNG = 19,        /*!< ble.png */
    MMAP_COFFEE_PJPG_CHEVRON_PNG = 20,        /*!< chevron.png */
    MMAP_COFFEE_PJPG_CHEVRON_1_PNG = 21,        /*!< chevron_1.png */
    MMAP_COFFEE_PJPG_CLEAN_PNG = 22,        /*!< clean.png */
    MMAP_COFFEE_PJPG_CUP_PNG = 23,        /*!< cup.png */
    MMAP_COFFEE_PJPG_CUP1_PNG = 24,        /*!< cup1.png */
    MMAP_COFFEE_PJPG_CUPS_PNG = 25,        /*!< cups.png */
    MMAP_COFFEE_PJPG_DISABLEDBEAN_PNG = 26,        /*!< disabledbean.png */
    MMAP_COFFEE_PJPG_DONE_PNG = 27,        /*!< done.png */
    MMAP_COFFEE_PJPG_DONE_60_PNG = 28,        /*!< done_60.png */
    MMAP_COFFEE_PJPG_FOAM_PNG = 29,        /*!< foam.png */
    MMAP_COFFEE_PJPG_FOAM_BODY_PNG = 30,        /*!< foam_body.png */
    MMAP_COFFEE_PJPG_LANGUAGES_PNG = 31,        /*!< languages.png */
    MMAP_COFFEE_PJPG_LIGHT_PNG = 32,        /*!< light.png */
    MMAP_COFFEE_PJPG_PARAMETERS_PNG = 33,        /*!< parameters.png */
    MMAP_COFFEE_PJPG_PARAMETERS_1_PNG = 34,        /*!< parameters_1.png */
    MMAP_COFFEE_PJPG_PROFILE_PNG = 35,        /*!< profile.png */
    MMAP_COFFEE_PJPG_QUANTITY_PNG = 36,        /*!< quantity.png */
    MMAP_COFFEE_PJPG_ROLLER_PNG = 37,        /*!< roller.png */
    MMAP_COFFEE_PJPG_SETTINGS_PNG = 38,        /*!< settings.png */
    MMAP_COFFEE_PJPG_SLIDER_BG_PNG = 39,        /*!< slider_bg.png */
    MMAP_COFFEE_PJPG_STANDBY_PNG = 40,        /*!< standby.png */
    MMAP_COFFEE_PJPG_TASTE1_PNG = 41,        /*!< taste1.png */
    MMAP_COFFEE_PJPG_TEMP_BODY_PNG = 42,        /*!< temp_body.png */
    MMAP_COFFEE_PJPG_TEMPERATURE_PNG = 43,        /*!< temperature.png */
    MMAP_COFFEE_PJPG_UNITS_PNG = 44,        /*!< units.png */
    MMAP_COFFEE_PJPG_WATER_PNG = 45,        /*!< water.png */
    MMAP_COFFEE_PJPG_WAVE1_PNG = 46,        /*!< wave1.png */
    MMAP_COFFEE_PJPG_WAVE_BOTTOM_PNG = 47,        /*!< wave_bottom.png */
    MMAP_COFFEE_PJPG_WAVEV1_PNG = 48,        /*!< wavev1.png */
    MMAP_COFFEE_PJPG_WAVEV2_PNG = 49,        /*!< wavev2.png */
    MMAP_COFFEE_PJPG_WIFI_PNG = 50,        /*!< wifi.png */
};
